Add sysid for shooter
CurtinFRC/2024-Offseason pull request #42
Opened 2024-06-13 09:14 UTC by Superbro525Alt

2024-06-14 12:25 UTC, spacey-sooty requested changes
Debugging stuff should be removed before merge 🙂

2024-07-28 04:24 UTC, Superbro525Alt commented
nuh uh

2024-07-28 05:55 UTC, Superbro525Alt commented
merge now

2024-07-28 05:57 UTC, spacey-sooty requested changes
You've committed multiple gitignored files remove them

2024-07-28 06:03 UTC, spacey-sooty requested changes
add back swerve docs

2024-07-28 06:03 UTC, spacey-sooty commented on src/main/java/frc/robot/Robot.java
> +    m_sysid.getAllCommands();
What does this do?

2024-07-28 06:12 UTC, Superbro525Alt commented on src/main/java/frc/robot/Robot.java
> +    m_sysid.getAllCommands();
it adds the functions to the class and the method returns a sequential command that runs all of the sysid things for all the subsystems added in forward and reverse

2024-07-28 06:26 UTC, spacey-sooty commented on src/main/java/frc/robot/Robot.java
> +    m_sysid.getAllCommands();
Surely the Sequential Command should be used somewhere

2024-07-28 09:32 UTC, spacey-sooty commented
How long does the Command to run? It could be nice to have a SysID auto for a practice match.

2024-08-07 11:12 UTC, closed without merging