Peter/ledintegration
CurtinFRC/2024-Offseason pull request #46
Opened 2024-06-16 06:49 UTC by SturrockPeter

Finished LED integration within arm states

2024-06-16 06:53 UTC, spacey-sooty commented
/format

2024-06-17 09:30 UTC, spacey-sooty requested changes
IMO we should display info about intaking and robot position as well.
Needs coordination with driveteam and @totallysomeoneyoudontknow
cc @Hazzer890 I'm sure you have an opinion on what the LEDs should do

2024-06-17 09:30 UTC, spacey-sooty commented on src/main/java/frc/robot/subsystems/Arm.java
> +        lEDPwm.setSpeed(0.99);
Could we have comments to say what that actually displays, its not obvious from the code

2024-06-17 09:30 UTC, spacey-sooty commented on src/main/java/frc/robot/subsystems/Arm.java
> +  PWM lEDPwm = new PWM(0);
this port needs to be determined still no?
```suggestion
  private PWM m_led = new PWM(0);
```

2024-06-20 10:39 UTC, SturrockPeter commented
> IMO we should display info about intaking and robot position as well. Needs coordination with driveteam and @totallysomeoneyoudontknow cc @Hazzer890 I'm sure you have an opinion on what the LEDs should do

currently working off LED patterns decided with Layla during season.

2024-06-20 10:41 UTC, SturrockPeter commented on src/main/java/frc/robot/subsystems/Arm.java
> +  PWM lEDPwm = new PWM(0);
> this port needs to be determined still no?

maybe, was going off memory, could also be port 1

2024-06-20 15:53 UTC, spacey-sooty requested changes

2024-06-20 15:53 UTC, spacey-sooty commented on src/main/java/frc/robot/subsystems/Arm.java
> +        lEDPwm.setSpeed(0.99); // blank //
Remove trailing slashes

2024-06-23 06:12 UTC, closed without merging